Repository RHEcosystemAppEng/cluster-iq, pull requests merged in 2024-12, with the labels that each got.

#66 V0.2
  Makefile
  README.md
  VERSION
  cmd/api/api_server.go
  cmd/api/db.go
  cmd/api/db_types.go
  cmd/api/handlers.go
  cmd/api/responseTypes.go
  cmd/scanner/scanner.go
  db/sql/clean.sql
  db/sql/init.sql
  db/sql/test_data.sql
  db/test_files/new-expense.json
  db/test_files/new-instance.json
  deployments/openshift/03_api.yaml
  deployments/openshift/04_scanner.yaml
  deployments/openshift/05_console.yaml
  doc/development-setup.md
  internal/inventory/account.go
  internal/inventory/account_test.go
  internal/inventory/cluster.go
  internal/inventory/cluster_test.go
  internal/inventory/common.go
  internal/inventory/expense.go
  internal/inventory/expense_test.go
  internal/inventory/instance.go
  internal/inventory/instance_test.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
  internal/inventory/providers.go
  internal/inventory/types.go
  internal/inventory/types_test.go
  internal/stocker/aws_billing.go
  internal/stocker/aws_common.go
  internal/stocker/aws_stocker.go
  open_api_design.yaml
Labels: bug, documentation, enhancement

#77 fix: remove unused handler body parameters
  Makefile
  cmd/api/api_server.go
  cmd/api/handlers.go
Labels: bug

#76 docs: enhance development setup documentation
  doc/development-setup.md
Labels: documentation

#84 docs: add additional validaton steps
  doc/development-setup.md
Labels: documentation

#83 chore: add dependency validation for required binaries
  Makefile
Labels: enhancement

#87 Added billing flag to Account. Billing module is disabled by default
  README.md
  cmd/scanner/scanner.go
  internal/inventory/account.go
Labels: documentation, enhancement

#86 fix: Fixed repeated names and added docs to SQL trigger and functions
  db/sql/init.sql
Labels: bug, documentation

#88 Dns console fix
  cmd/api/handlers.go
  deployments/containerfiles/Containerfile-api
  deployments/containerfiles/Containerfile-scanner
  go.mod
  go.sum
  internal/stocker/aws_stocker.go
  internal/stocker/aws_stocker_ec2.go
  internal/stocker/aws_stocker_route53.go
  internal/stocker/aws_stocker_tags.go
Labels: bug, enhancement

#91 fix: OpenAPI schema improvements
  cmd/api/handlers.go
Labels: documentation

#95 fix: always pull container images from repository
  Makefile
  deployments/compose/compose-devel.yaml
Labels: enhancement, good first issue
