Repository RHEcosystemAppEng/cluster-iq, pull requests merged in 2025-02, with the labels that each got.

#107 Release 0.3 rc 1
  README.md
  deployments/containerfiles/Containerfile-agent
  deployments/containerfiles/Containerfile-api
  deployments/containerfiles/Containerfile-scanner
  deployments/helm/cluster-iq/Chart.yaml
  deployments/helm/cluster-iq/templates/_helpers.tpl
  deployments/helm/cluster-iq/templates/agent/configmap.yaml
  deployments/helm/cluster-iq/templates/agent/deployment.yaml
  deployments/helm/cluster-iq/templates/agent/service.yaml
  deployments/helm/cluster-iq/templates/agent/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/api/configmap.yaml
  deployments/helm/cluster-iq/values.yaml
  doc/architecture.png
  doc/architecture.xoj
Labels: documentation

#113 chore: reorganize server structure and improve shutdown handling
  cmd/api/handlers.go
  cmd/api/router.go
  cmd/api/server.go
  internal/middleware/middlware.go
Labels: chore

#117 fix: Assigned CostExplorer service client connection correctly
  internal/cloud_providers/aws/aws-cost-explorer.go
Labels: bug

#119 fix: typo on function 'setupSwagger'
  cmd/api/router.go
Labels: bug

#136 doc: Documented ClusterIQ AWS user creation
  README.md
  doc/aws-cluster-iq-policy.json
  doc/aws-policy-setup-01.png
  doc/aws-policy-setup-02.png
  doc/aws-user-access-key-01.png
  doc/aws-user-access-key-02.png
  doc/aws-user-permissions-config.md
  doc/aws-user-setup-01.png
  doc/aws-user-setup-02.png
  doc/aws-user-setup-03.png
Labels: documentation

#131 feat: implement audit logging system
  README.md
  cmd/api/handlers.go
  cmd/api/response_types.go
  cmd/api/router.go
  cmd/api/server.go
  cmd/api/sql_client.go
  cmd/api/sql_queries.go
  db/sql/init.sql
  doc/events/README.md
  doc/events/power-action-sequence.md
  internal/events/events.go
  internal/events/types.go
  internal/inventory/types.go
  internal/models/models.go
Labels: enhancement

#138 feat: code linting, formatting using GH actions
  .github/workflows/container-image-building.yaml
  .github/workflows/go-lint-and-format.yml
  .golangci.yaml
Labels: enhancement
