Repository RHEcosystemAppEng/cluster-iq, pull requests merged in 2025-04, with the labels that each got.

#151 bug: avoid redundant inventory refresh on non-relevant endpoints
  cmd/api/router.go
  internal/sql_client/sql_client.go
Labels: bug

#155 refactor: efficient clusters power management
  internal/cloud_executors/aws.go
  internal/cloud_providers/aws/aws-ec2.go
Labels: chore

#156 chore: Added cost info for clusters (last month, current month so far…
  db/sql/init.sql
  internal/inventory/cluster.go
Labels: enhancement
