Repository RHEcosystemAppEng/cluster-iq, pull requests merged in 2025-01, with the labels that each got.

#100 security: update x/crypto to v0.31.0
  go.mod
  go.sum
Labels: security

#99 chore: makefile standardization
  Makefile
  deployments/compose/compose-devel.yaml
Labels: enhancement

#101 feat: add Helm chart
  deployments/helm/cluster-iq/.helmignore
  deployments/helm/cluster-iq/Chart.yaml
  deployments/helm/cluster-iq/README.md
  deployments/helm/cluster-iq/templates/_helpers.tpl
  deployments/helm/cluster-iq/templates/api/configmap.yaml
  deployments/helm/cluster-iq/templates/api/deployment.yaml
  deployments/helm/cluster-iq/templates/api/service.yaml
  deployments/helm/cluster-iq/templates/api/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/console/configmap_nginx_init.yaml
  deployments/helm/cluster-iq/templates/console/configmap_nginx_template.yaml
  deployments/helm/cluster-iq/templates/console/deployment.yaml
  deployments/helm/cluster-iq/templates/console/route.yaml
  deployments/helm/cluster-iq/templates/console/service.yaml
  deployments/helm/cluster-iq/templates/console/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/database/configmap-init.yaml
  deployments/helm/cluster-iq/templates/database/job.yaml
  deployments/helm/cluster-iq/templates/database/secret.yaml
  deployments/helm/cluster-iq/templates/database/service.yaml
  deployments/helm/cluster-iq/templates/database/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/database/statefulset.yaml
  deployments/helm/cluster-iq/templates/scanner/configmap.yaml
  deployments/helm/cluster-iq/templates/scanner/cronjob.yaml
  deployments/helm/cluster-iq/values.yaml
Labels: enhancement

#102 feat: add Helm chart (#101)
  deployments/helm/cluster-iq/.helmignore
  deployments/helm/cluster-iq/Chart.yaml
  deployments/helm/cluster-iq/README.md
  deployments/helm/cluster-iq/templates/_helpers.tpl
  deployments/helm/cluster-iq/templates/api/configmap.yaml
  deployments/helm/cluster-iq/templates/api/deployment.yaml
  deployments/helm/cluster-iq/templates/api/service.yaml
  deployments/helm/cluster-iq/templates/api/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/console/configmap_nginx_init.yaml
  deployments/helm/cluster-iq/templates/console/configmap_nginx_template.yaml
  deployments/helm/cluster-iq/templates/console/deployment.yaml
  deployments/helm/cluster-iq/templates/console/route.yaml
  deployments/helm/cluster-iq/templates/console/service.yaml
  deployments/helm/cluster-iq/templates/console/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/database/configmap-init.yaml
  deployments/helm/cluster-iq/templates/database/job.yaml
  deployments/helm/cluster-iq/templates/database/secret.yaml
  deployments/helm/cluster-iq/templates/database/service.yaml
  deployments/helm/cluster-iq/templates/database/serviceaccount.yaml
  deployments/helm/cluster-iq/templates/database/statefulset.yaml
  deployments/helm/cluster-iq/templates/scanner/configmap.yaml
  deployments/helm/cluster-iq/templates/scanner/cronjob.yaml
  deployments/helm/cluster-iq/values.yaml
Labels: duplicate, enhancement

#103 feat: cloud provider lib implementation
  Makefile
  internal/cloud_agent/aws.go
  internal/cloud_agent/cloud_agent.go
  internal/cloud_providers/aws/aws-cost-explorer.go
  internal/cloud_providers/aws/aws-ec2.go
  internal/cloud_providers/aws/aws-route53.go
  internal/cloud_providers/aws/aws-sts.go
  internal/cloud_providers/aws/aws-tags.go
  internal/cloud_providers/aws/aws.go
  internal/cloud_providers/cloud_provider.go
  internal/config/agent_config.go
  internal/config/api_config.go
  internal/config/config.go
  internal/config/scanner_config.go
  internal/inventory/cluster.go
  internal/inventory/tag.go
  internal/inventory/types.go
  internal/stocker/aws_billing.go
  internal/stocker/aws_common.go
  internal/stocker/aws_stocker.go
  internal/stocker/aws_stocker_ec2.go
  internal/stocker/aws_stocker_route53.go
  internal/stocker/aws_stocker_tags.go
Labels: enhancement

#104 Cloud agent
  .dockerignore
  .gitignore
  Makefile
  cmd/agent/agent.go
  cmd/agent/agent_rpc.go
  cmd/agent/proto/agent.proto
  cmd/api/api_server.go
  cmd/api/db.go
  cmd/api/db_types.go
  cmd/api/grpc_client.go
  cmd/api/handlers.go
  cmd/api/responseTypes.go
  cmd/api/response_types.go
  cmd/api/server.go
  cmd/api/sql_client.go
  cmd/api/sql_queries.go
  cmd/api/status_requests.go
  deployments/compose/compose-devel.yaml
  deployments/containerfiles/Containerfile-agent
  go.mod
  go.sum
  internal/cloud_executors/aws.go
  internal/cloud_executors/cloud_executor.go
  internal/cloud_providers/aws/aws-ec2.go
  internal/cloud_providers/aws/aws.go
  internal/config/agent_config.go
  internal/config/api_config.go
Labels: enhancement

#108 fix: correctly determine EC2 instance creation timestamp
  internal/cloud_providers/aws/aws-ec2.go
Labels: bug
