Repository RHEcosystemAppEng/cluster-iq, pull requests merged in 2025-07, with the labels that each got.

#198 feat: added last scan date to the Overview API
  cmd/api/handlers.go
  internal/models/models.go
  internal/sql_client/sql_client.go
  internal/sql_client/sql_queries.go
Labels: enhancement

#202 Refactor GHActions workflows
  .github/workflows/build-container-images.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/unit-tests.yaml
  .github/workflows/validate-pr.yaml
  .gitignore
  Makefile
  deployments/compose/compose-gh.yaml
  test/integration/api_test.go
Labels: enhancement

#207 Bug/scanner post error 205
  cmd/api/router.go
  cmd/scanner/scanner.go
  db/sql/init.sql
Labels: bug

#204 feat: Added instances summary by states to overview API endpoint
  internal/models/models.go
  internal/sql_client/sql_queries.go
Labels: enhancement, chore
